### ISSUE TITLE
UART1 reserved internally

### ISSUE THREAD

**Issue by abl73** [garethm79/hanover_flipdot_esphome#4]
Prepared an ESP32 with this code (to hopefully get my Hanover display working), but got the following error when trying to install:

INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/hanoverflipdot.yaml...
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

uart: [source <unicode string>:38]
  - 
    ID 'uart1' is reserved internally and cannot be used.
    id: uart1
    tx_pin: GPIO2
    baud_rate: 4800
display.hanover_flipdot: [source <unicode string>:43]
  platform: hanover_flipdot
  id: flipdot1
  
  ID 'uart1' is reserved internally and cannot be used.
  uart_id: uart1
  width: 28
  height: 14
  address: 1
  update_interval: 10s
  offset: 1
  rotation: 180
  pages: 
    - id: page1
      lambda: |-
        it.print(it.get_width() /2, it.get_height()/2, id(_0705N1E1), TextAlign::CENTER, "Hello");
    - id: page2
      lambda: |-
        it.print(it.get_width() /2, it.get_height()/2, id(_0705N1E1), TextAlign::CENTER, "World");

**Comment by abl73** [comment]
Just did some further googling, and I changed uart1 to uart_0, which seems to work...
One final question I have what the id number is _0705N1E1?

**Comment by abl73** [comment]
Apparently this is the reference to the font, which can't be downloaded anymore via the link mentioned in the read me. So added some code that refer to font that should be used (and then replace _0705N1E1 by my_font (which made the code work and uploaded to the esp:

font:
  - file: "hanover.ttf"
    id: my_font
    size: 20

**Comment by garethm79** [comment]
@abl73 Hiya, sorry meant to reply earlier. Yes I think there has been an internal change and uart1 is now a reserved name, I will update it to fix that. The font 0705N1E1 is Hanover proprietary font I extracted from some official design software and is not included I don't think it's a good idea to publish copyright material, even though it's a pretty niche thing!  It will work with any font though, some work better than others.

**Comment by abl73** [comment]
No problem at all, I always try to first do my best but sometimes writing it down helps me to think clearly...
If I may ask another question: I bought a rs485 module (https://www.haljia.com/products/haljia-5v-max485-module-rs485-module-ttl-to-rs-485-module-converter-board-compatible-with-arduino) which, now that I build it, has quite a different layout compared to the instructions (no pins 3 and 4 where a resistor would be needed and on the input side DI, DE, RE, RD. Which one would need to be connected to GPI02 on my ESP32? And does that module need power somehow (on output side VCC and Ground)?

**Comment by garethm79** [comment]
> No problem at all, I always try to first do my best but sometimes writing it down helps me to think clearly... If I may ask another question: I bought a rs485 module (https://www.haljia.com/products/haljia-5v-max485-module-rs485-module-ttl-to-rs-485-module-converter-board-compatible-with-arduino) which, now that I build it, has quite a different layout compared to the instructions (no pins 3 and 4 where a resistor would be needed and on the input side DI, DE, RE, RD. Which one would need to be connected to GPI02 on my ESP32? And does that module need power somehow (on output side VCC and Ground)?

I do own those but never found them quite as reliable as the other more common type which controls that automatically. However I think you should be able to just tie DE and RE to 3V3, since you only need to transmit: https://electronics.stackexchange.com/questions/153500/correctly-using-re-and-de-with-rs485
The VCC will need connecting to a 3V3 pin, and GND to any ground pin. DI (data in) will need connecting to the output pin from the ESP32. I don't connect the RO (receiver output) to anything, but just doing some reading it should probably be tied to GND.

**Comment by abl73** [comment]
Thanks for your help. Tried your instructions.
- Tied DE and RE together with VCC to 3v3 pin on the ESP32.
- GND to GND on ESP32.
- DI to GPIO2 (D2) on ESP32.
- Tried RO unconnected as well as to GND.

After these combinations I installed via ESPHome to my ESP32 and unfortunately nothing happens on my display.

My full code:
`esphome:
  name: hanoverflipdot
  friendly_name: hanoverflipdot

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XHNzQFJetnMjLQVNhPr/TwWpemFTSOmUSYRBultgm/s="

ota:
  password: "4894db5fe436bf4023d8bb61a5359a1e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hanoverflipdot Fallback Hotspot"
    password: "3Oi3meYxbLRI"

captive_portal:

font:
  - file: "hanover.ttf"
    id: my_font
    size: 20

external_components:
  - source:
      type: local
      path: custom_components # The name of the folder we created

uart:
  - id: uart_0
    tx_pin: GPIO2
    baud_rate: 4800
  
display:
  - platform: hanover_flipdot
    id: flipdot1
    uart_id: uart_0
    
    width: 84 
    height: 8
    # Self-explanatory!

    address: 0x01
    # This should match the rotary switch on the control board
    
    update_interval: 10s
    # This is how often the display is updated. The flipdots take some time to update, it makes makes a whining noise, and presumably does stress the components somewhat, so it can't be done too rapidly, especially on larger displays. You will need to adjust this depending on your use. eg. if displaying a temperature you might only need to update it every couple of minutes.

    offset: 1 
    # Shifts the display up or down by 1 pixel. I need to do this on only one of my displays and I haven't yet figured out why...
    
    rotation: 180 
    # This is a built-in feature of ESPHome and works off the display buffer, the display cases are wedge shaped and when freestanding are best sat upside-down!

# Below is all pretty standard ESPHome display code. I'd recommend buying a cheap mini OLED display to get used to programming it.

    pages:
      - id: page1
        lambda: |-
          it.print(it.get_width() /2, it.get_height()/2, id(my_font), TextAlign::CENTER, "Hello");
          
      - id: page2
        lambda: |-
          it.print(it.get_width() /2, it.get_height()/2, id(my_font), TextAlign::CENTER, "World");

interval:
 - interval: 10s
   then:
     - display.page.show_next: flipdot1
     - component.update: flipdot1`

**Comment by abl73** [comment]
Bought another device (in the hope it is the same device you used): https://www.amazon.com.be/dp/B09VGJCJKQ?psc=1&ref=ppx_yo2ov_dt_b_product_details

Connected the following:

ESP<------>RS485<------->Hanover
3v3---------VCC
Ground-----Ground
D2---------- RXD
..........................A+--------------A+ (red cable)
...........................B---------------B- (black cable)

Didn't use the resistor as I didn't understand where pin 3 and 4 would be...

**Comment by abl73** [comment]
Just saw that the RXD should be TXD, changed that but still no solution...
Can see that the RS485 module TX led blinks red every 10 seconds, so seems to work. Thought it may be helpful to include a bit of the log:

[17:54:10][C][logger:439]: Logger:
[17:54:10][C][logger:440]:   Level: DEBUG
[17:54:10][C][logger:441]:   Log Baud Rate: 115200
[17:54:10][C][logger:443]:   Hardware UART: UART0
[17:54:10][C][uart.arduino_esp32:137]: UART Bus 1:
[17:54:10][C][uart.arduino_esp32:138]:   TX Pin: GPIO2
[17:54:10][C][uart.arduino_esp32:143]:   Baud Rate: 4800 baud
[17:54:10][C][uart.arduino_esp32:144]:   Data Bits: 8
[17:54:10][C][uart.arduino_esp32:145]:   Parity: NONE
[17:54:10][C][uart.arduino_esp32:146]:   Stop bits: 1
[17:54:10][D][custom:129]: hanover_flipdot::dump_config
[17:54:10][C][hanover_flipdot:131]: hanover_flipdot
[17:54:10][C][hanover_flipdot:131]:   Rotations: 180 °
[17:54:10][C][hanover_flipdot:131]:   Dimensions: 84px x 8px
[17:54:10][C][hanover_flipdot:135]:   Update Interval: 10.0s
[17:54:10][C][captive_portal:088]: Captive Portal:
[17:54:10][C][mdns:115]: mDNS:
[17:54:10][C][mdns:116]:   Hostname: hanover
[17:54:10][C][ota:097]: Over-The-Air Updates:
[17:54:10][C][ota:098]:   Address: hanover.local:3232
[17:54:10][C][ota:101]:   Using Password.
[17:54:10][C][api:139]: API Server:
[17:54:10][C][api:140]:   Address: hanover.local:6053
[17:54:10][C][api:142]:   Using noise encryption: YES
[17:54:15][D][custom:049]: hanover_flipdot::display
[17:54:16][W][component:214]: Component interval took a long time for an operation (0.25 s).
[17:54:16][W][component:215]: Components should block for at most 20-30ms.
[17:54:17][D][custom:049]: hanover_flipdot::display

**Comment by abl73** [comment]
Did some further reading and saw that my indicator is on position 1 (so address should be 0x02)... after changing the text size and the orientation all working now perfectly! Thanks Gareth for providing this great code, much appreciated. If you have some hints about how to have it interact with MQTT (so that the text can be more dynamic), I would be quite interested...
